<?php

use Illuminate\Database\Seeder;

class SectsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('sects')->insert(['name' => 'Kiếm sư', 'icon_url' => 'https://raw.githubusercontent.com/bnsvn/bnsvn.github.io/master/images/class/bm.png', 'abstract' => 'Kiếm Sư là hệ phái công thủ toàn diện, sử dụng vũ khí kiếm để áp chế đối thủ trên chiến trường. Võ công của Kiếm Sư dựa trên tốc độ tấn công nhanh và kĩ thuật di chuyển xung quanh địch thủ. Kiếm Sư có thể né tránh và đỡ đòn của đối phương mà không phải ngưng trệ, cũng như phản công quyết liệt với những tuyệt chiêu của mình.', 'element' => 'Khí Kiếm, Khoái Kiếm, Ngự Kiếm',]);
        DB::table('sects')->insert(['name' => 'Kiếm vũ', 'icon_url' => 'https://raw.githubusercontent.com/bnsvn/bnsvn.github.io/master/images/class/bd.png', 'abstract' => 'Kiếm Vũ được biết đến với những đòn tấn công nhanh, biến hóa và những chiêu thức diện rộng thay cho những kỹ năng phòng ngự. Kiếm Vũ di chuyển với một tốc độ phi thường khiến cho đối phương không có cơ hội tấn công. Với thể chất đặc biệt cùng những chiêu thức huyền bí, những Kiếm Vũ có thể hạ gục kẻ thủ một cách chóng vánh trong sự bất lực của chúng.', 'element' => 'Phong Vân, Lôi Quang, Quỷ Kiếm',]);
        DB::table('sects')->insert(['name' => 'Sát thủ', 'icon_url' => 'https://raw.githubusercontent.com/bnsvn/bnsvn.github.io/master/images/class/sin.png', 'abstract' => 'Sát Thủ tiêu hao sinh lực địch bằng những đòn tấn công chớp nhoáng, hạ độc và làm cho vết thương chảy máu không ngừng. Bí kíp lợi hại nhất của những Sát Thủ chính là những chiêu thức biến ảo khiến họ trở nên vô hình trước mắt kẻ thù, thoắt ẩn thoắt hiện trên chiến trường và thậm chí là hoán đổi vị trí với đối thủ.', 'element' => 'Độc Linh, Vô Linh, Ám Linh',]);
        DB::table('sects')->insert(['name' => 'Cuồng long', 'icon_url' => 'https://raw.githubusercontent.com/bnsvn/bnsvn.github.io/master/images/class/des.png', 'abstract' => 'Đúng như tên gọi của mình, Cuồng Long sở hữu kỹ năng hủy diệt mạnh nhất của Blade and Soul. Thể hình ngoại cỡ thường khiến họ trở thành mục tiêu tấn công chính của kẻ thù. Tuy nhiên, dù cho kẻ thù dù hung hãn đến đâu, những Cuồng Long vẫn có thể dễ dàng loại bỏ những kẻ đang cố gắng cản bước họ.', 'element' => 'Thái Sơn, Hắc Ám, Hộ Mệnh',]);
        DB::table('sects')->insert(['name' => 'Võ sư', 'icon_url' => 'https://raw.githubusercontent.com/bnsvn/bnsvn.github.io/master/images/class/kfm.png', 'abstract' => 'Võ Sư sử dụng quyền cước để đánh bại đối thủ, nhưng sức mạnh thật sự của hệ phái này nằm ở việc nắm bắt thời điểm xuất chiêu. Lấy "dĩ nhu chế cương" làm tâm pháp, Võ Sư có thể bắt được đòn tấn công của đối phương, chuyển hướng đòn đánh và phản công trong nháy mắt.', 'element' => 'Xích Hổ, Thanh Long, Hắc Lang',]);
        DB::table('sects')->insert(['name' => 'Pháp sư', 'icon_url' => 'https://raw.githubusercontent.com/bnsvn/bnsvn.github.io/master/images/class/fm.png', 'abstract' => 'Pháp Sư là hệ phái điều khiển các yếu tố tự nhiên theo ý muốn của mình: Hỏa Tuyệt Kĩ với khả năng dồn sát thương và tấn công liên tục; hay Băng Tuyệt Kĩ với tác dụng cầm chân kẻ địch và cường hóa khả năng phòng thủ. Ở đẳng cấp cao, Pháp Sư có thể trói cứng kẻ địch giữa không trung, khiến chúng trở thành mục tiêu của các đòn tấn công mà không thể chống đỡ.', 'element' => 'Siêu Nhiệt, Cực Hàn, Âm Dương',]);
        DB::table('sects')->insert(['name' => 'Triệu hồi sư', 'icon_url' => 'https://raw.githubusercontent.com/bnsvn/bnsvn.github.io/master/images/class/sum.png', 'abstract' => 'Triệu Hồi Sư là hệ phái tập trung vào việc điều khiển và phối hợp cùng Linh Thú để khống chế và đánh bại kẻ địch. Linh Thú sẽ đảm nhiệm việc tiếp cận, gây sát thương vật lý và thu hút sự chú ý của đối phương. Trong khi đó, Triệu Hồi Sư sẽ hỗ trợ người bạn của mình bằng kĩ năng tầm xa: tăng sức mạnh cho Linh Thú hoặc tấn công kẻ địch chung của cả hai.', 'element' => 'Tạo Hóa, Thiên Nhiên, Hoán Thú',]);
        DB::table('sects')->insert(['name' => 'Khí công sư', 'icon_url' => 'https://raw.githubusercontent.com/bnsvn/bnsvn.github.io/master/images/class/sf.png', 'abstract' => 'Kết hợp giữa phép thuật và võ thuật, Khí Công Sư thực sự mang lại luồng gió mới cho tựa game Blade & Soul. Chỉ với một nút bấm, bạn có thể nhanh chóng chuyển đổi giữa hai thế đánh xa – sử dụng phép thuật và đánh gần – sử dụng võ thuật.', 'element' => 'Tuần Hoàn, Kim Cang, Thiên Thọ',]);
        DB::table('sects')->insert(['name' => 'Thuật sư', 'icon_url' => 'https://raw.githubusercontent.com/bnsvn/bnsvn.github.io/master/images/class/wl.png', 'abstract' => 'Khai thác sức mạnh của ma thuật hắc ám, sức mạnh của Thuật Sư nằm ở những lá Bùa ẩn chứa đựng nguồn sức mạnh siêu nhiên từ những dòng chữ bí ẩn, có thể tạo ra những hiệu ứng không thể tin nổi, cả trong tấn công lẫn phòng ngự. Thông qua những lá bùa này, các Thuật Sư có thể Triệu hồi quái vật, hoặc biến chúng thành những vũ khí để kiềm tỏa kẻ thù.', 'element' => 'Thời Không, Thần Chú, Nhập Hồn',]);
        DB::table('sects')->insert(['name' => 'Xạ thủ', 'icon_url' => 'https://raw.githubusercontent.com/bnsvn/bnsvn.github.io/master/images/class/gun.png', 'abstract' => 'Xạ Thủ không chỉ là những bậc thầy, còn là một nghệ sỹ trên chiến trường. Bên cạnh khả năng tiêu diệt những đối thủ cứng cựa nhất từ cự ly xa với cặp súng lục trong tay, Xạ Thủ còn có thể di chuyển cực kỳ linh hoạt cả trong tấn công và phòng ngự nhờ chiếc móc của mình.', 'element' => 'Hỏa Lực, Ma Đạn, Tốc Xạ',]);
        DB::table('sects')->insert(['name' => 'Đấu sĩ', 'icon_url' => 'https://raw.githubusercontent.com/bnsvn/bnsvn.github.io/master/images/class/wr.png', 'abstract' => 'Lấy Đại Kiếm để trấn áp địch thủ, các đòn tấn công của Đấu Sĩ tuy có phần chậm chạp nhưng lại sở hữu uy lực vô cùng lớn. Đây là hệ phái cận chiến có thể giảm sát thương nhận vào từ kẻ địch hoặc kháng hiệu ứng trạng thái bằng Cường Thể khi đang có Thiên Kiếm Trận bằng cách tấn công liên tục.', 'element' => 'Huyết Khí, Thiên Kiếm, Tuyệt Thế',]);
        DB::table('sects')->insert(['name' => 'Cung thủ', 'icon_url' => 'https://raw.githubusercontent.com/bnsvn/bnsvn.github.io/master/images/class/ac.png', 'abstract' => '', 'element' => '',]);
    }
}
